languageCode = 'en-us'
title = '/home/blog'
theme = 'Steak'

[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
