---
name: On Merge

on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: ghcr.io/philgood/bloghugo
  PACKAGE_NAME: bloghugo
  
jobs:
  release-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Build
        uses: ./.github/actions/docker-image
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          latest: true
