---
name: On Merge

on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: ghcr.io/philgood/bloghugo
  PACKAGE_NAME: bloghugo
  
jobs:
  release-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc

      - name: Build
        uses: ./.github/actions/docker-image
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          latest: true
