---
name: On Merge

on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: ghcr.io/philgood/bloghugo
  PACKAGE_NAME: bloghugo
  
jobs:
  release-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@2d7d9f7ff5b310f983d059b68785b3c74d8b8edd

      - name: Build
        uses: ./.github/actions/docker-image
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          latest: true
